### ISSUE TITLE
Choosing Pera Wallet on flutter web will take to App Store on iPhone

### ISSUE THREAD

**Issue by jasonhtpham** [nextchapterstudio/walletconnect_qrcode_modal_dart#28]
If I run my DApp on using `flutter web` and use iPhone to connect to the Pera Wallet. When presented with a list of wallets to connect, choosing Pera Wallet will always take me to the App Store instead of the Pera Wallet app (I have the app already installed and updated). 

Is there any way I could make any changes to this? Or this is a bug in the package (or in the `wallet-connect-dart` package?

**Comment by 3ph** [comment]
I did a bit of investigation and this is mainly caused by Para Wallet not using universal links but (older) deep links. There are restrictions about querying these on iOS (reference https://developer.apple.com/documentation/uikit/uiapplication/1622952-canopenurl). So unless you add the deep link scheme to your `LSApplicationQueriesSchemes`, the package will treat the link as unopenable and redirects you to App Store.

One way of handling this is to ignore the check for deep links and try to open them anyway. This is what the web package seems to be doing. The downside is that if the corresponding Wallet app is not installed, rather than being redirected to App Store, you will receive an error message.

I will release an update for this, you will be able to configure the behavior.

**Comment by jasonhtpham** [comment]
Thank you for your timely response! I am looking forward to your updates.

**Comment by jasonhtpham** [comment]
Thank you for your quick update on the package. I just tested, and choosing Pera Wallet can now open the app. 

However, it does not show any popup for connecting to an account. I am assuming that the popup should appear when I land on the Pera Wallet app. This might be the issue with the URL, I guess?

**Comment by 3ph** [comment]
Yes, this is an issue with the deep link scheme registered for Pera Wallet. According to [this](https://github.com/perawallet/pera-wallet/issues/81) the Pera Wallet is using `algorand-wc` scheme but registry record contains:

```json
"mobile": {
      "native": "algorand://",
      "universal": null
    },
```

I've tested with `algorand-wc` and the Pera Wallet recognizes the link. I'm checking WC team that the package still uses the correct registry data (with V2 migration stuff might have moved as well). I suspect it is still the accurate registry data and in that case, the Para Wallet team would have to fix their WC registry entry for this to work properly.

**Comment by jasonhtpham** [comment]
Thank you for your timely support @3ph!! I am looking forward to the solution.

**Comment by 3ph** [comment]
I have checked the current listings API (as documented [here](https://docs.walletconnect.com/2.0/cloud/explorer#listings)) and it contains the same data - the native link is the same `algorand://`. You will have to contact the Pera Wallet team to fix the listing (or add support for `algorand://` scheme).
