### ISSUE TITLE
Customising Modal

### ISSUE THREAD

**Issue by ZeroTimeDrift** [nextchapterstudio/walletconnect_qrcode_modal_dart#30]
When I connect the modal, on the mobile screen I only have the option of pressing 'connect' on mobile, which does redirect me to metamask, I don't have the choice of multiple wallets. I do only have MetaMask installed, but my impression was that it'd still come up with all the wallet options. Is this normal? If so, how can I add other wallets.

**Comment by 3ph** [comment]
Yes, that is expected behaviour - please see https://github.com/nextchapterstudio/walletconnect_qrcode_modal_dart/issues/7 and https://github.com/nextchapterstudio/walletconnect_qrcode_modal_dart/issues/17.

Also see [Mobile Linking](https://docs.walletconnect.com/1.0/mobile-linking) in WalletConnect docs.
