### ISSUE TITLE
How to choose a wallet to open on Android?

### ISSUE THREAD

**Issue by peyton-v5** [nextchapterstudio/walletconnect_qrcode_modal_dart#7]
While knowing that the plugin doesn't support Android selection, I have this need. Hope you can tell me how to choose android

**Comment by 3ph** [comment]
Android supports this out of the box - multiple applications can register for the same schema, you will see the selection as the system dialog rather than an app dialog (unlike iOS where one schema can be only registered by a single app).

Please have a look at the official WalletConnect mobile linking documentation - we are trying to keep this plugin consistent with the official one.
